language: node_js
node_js:
  - 10

script:
  - npm run lint
  - npm run test
  - quasar build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/spa
  fqdn: minipost.lipbcu.love
  on:
    branch: master
